Make AD script more robust
Signed-off-by: Dave Brown <d.brown@bigdavedev.com>

diff --git a/bin/add_machine_to_domain b/bin/add_machine_to_domain
--- a/bin/add_machine_to_domain
+++ b/bin/add_machine_to_domain
@@ -1,13 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-script_name=$(basename $0)
+script_name=$(/usr/bin/basename ${0})
 
 function usage {
-    echo "usage: ${script_name} [dgus]"
-    echo "      -d       specify which domain to join"
-    echo "      -g       specify which domain group to require membership of"
-    echo "      -u       specify the user with which to join to the domain"
-    echo "      -s       indicate that this machine is a server"
+    /bin/echo "usage: ${script_name} -[dgirsu]"
+    /bin/echo "      -d       specify which domain to join"
+    /bin/echo "      -g       specify which domain group to require membership of"
+    /bin/echo "      -i       Install PBIS"
+    /bin/echo "      -r       remove Posix user from system"
+    /bin/echo "      -s       indicate that this machine is a server"
+    /bin/echo "      -u       specify the user with which to join to the domain"
     exit 1
 }
 
@@ -15,63 +17,99 @@ if [ $# == 0 ]; then
     usage
 fi
 
-pushd /tmp
-    wget http://download.beyondtrust.com/PBISO/8.3/pbis-open-8.3.0.3287.linux.x86_64.deb.sh
-    bash pbis-open-8.3.0.3287.linux.x86_64.deb.sh
-    rm -rf pbis*
-popd
-
-PBIS_CONFIG=/opt/pbis/bin/config
-
-while getopts ":u:d:g:s" opt; do
-  case $opt in
-    u)
-      DOMAIN_USER=${OPTARG}
-      ;;
-    d)
-      DOMAIN=${OPTARG}
-      ;;
-    g)
-      DOMAIN_GROUP=${OPTARG}
-      ;;
-    s)
-      IS_SERVER=1
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-      ;;
-  esac
+while getopts ":d:g:u:irs" opt; do
+    case ${opt} in
+        d)
+            DOMAIN=${OPTARG}
+            ;;
+        g)
+            DOMAIN_GROUP=${OPTARG}
+            ;;
+        i)
+            INSTALL_PBIS=1
+            ;;
+        r)
+            REMOVE_POSIX_USER=1
+            ;;
+        s)
+            IS_SERVER=1
+            ;;
+        u)
+            DOMAIN_USER=${OPTARG}
+            ;;
+        \?)
+            /bin/echo "Invalid option: -${OPTARG}" >&2
+            exit 1
+            ;;
+        :)
+            /bin/echo "Option -${OPTARG} requires an argument." >&2
+            exit 1
+            ;;
+    esac
 done
 
-domainjoin-cli join --disable ssh ${DOMAIN}.loc ${DOMAIN_USER}@${DOMAIN}.loc
-sed -i 's/session optional pam_lsass.so/session [success=ok default=ignore] pam_lsass.so/' /etc/pam.d/common-session
+if [ ${INSTALL_PBIS} ]; then
+    /bin/echo "*******************************************************************************"
+    /bin/echo "**                            Installing PBIS 8.3                            **"
+    /bin/echo "*******************************************************************************"
+    pushd /tmp
+        /usr/bin/wget http://download.beyondtrust.com/PBISO/8.3/pbis-open-8.3.0.3287.linux.x86_64.deb.sh
+        /bin/bash -e pbis-open-8.3.0.3287.linux.x86_64.deb.sh
+        /bin/rm --recursive --force pbis*
+    popd
+fi
+
+PBIS_HOME=/opt/pbis
+PBIS_CONFIG=${PBIS_HOME}/bin/config
+
+if [ ! -e ${PBIS_HOME}/bin/domainjoin-cli ]; then
+    echo "You need to install PBIS first; Re-run with -i to install."
+    exit 1
+fi
+
+if [ ! ${IS_SERVER} ]; then
+    DOMAINJOIN_ARGS="--disable ssh"
+else
+    DOMAINJOIN_ARGS=
+fi
+
+${PBIS_HOME}/bin/domainjoin-cli join ${DOMAINJOIN_ARGS} ${DOMAIN}.loc ${DOMAIN_USER}@${DOMAIN}.loc
+/bin/sed --in-place 's/session\toptional\tpam_lsass.so/session\t[success=ok default=ignore]\tpam_lsass.so/' /etc/pam.d/common-session
 ${PBIS_CONFIG} Requiremembershipof "${DOMAIN}\\${DOMAIN_GROUP}"
 ${PBIS_CONFIG} HomeDirTemplate "%H/%U"
 ${PBIS_CONFIG} LoginShellTemplate "/bin/bash"
 ${PBIS_CONFIG} UserDomainPrefix "${DOMAIN}.loc"
 ${PBIS_CONFIG} AssumeDefaultDomain true
 
-cat >> /etc/sudoers.d/${DOMAIN}_domain << EOF
+/bin/cat >> /etc/sudoers.d/${DOMAIN}_domain << EOF
 # Afford Linux admins their sudo rights
 %${DOMAIN}\\\\${DOMAIN_GROUP} ALL=(ALL:ALL) ALL
 EOF
 
-if [ ${IS_SERVER} ]; then
-    echo "Server config done"
-    exit 0
+if [ ${REMOVE_POSIX_USER} ]; then
+    /bin/echo "*******************************************************************************"
+    /bin/echo "**                 Removing user ${DOMAIN_USER} from system!                 **"
+    /bin/echo "*******************************************************************************"
+    UID=$(/usr/bin/id -u ${DOMAIN_USER})
+    /usr/sbin/deluser ${DOMAIN_USER}
+    /usr/bin/find /home -uid ${UID} -exec /bin/chown ${DOMAIN}\\${DOMAIN_USER}:${DOMAIN}\\${DOMAIN_GROUP}
 fi
 
-echo "Desktop machine; fix greeter"
+if [ ${IS_SERVER} ]; then
+    /bin/echo "*******************************************************************************"
+    /bin/echo "**                            Server config done                             **"
+    /bin/echo "*******************************************************************************"
+elif [ ! -z $(/usr/bin/which unity-greeter) ]; then
+    /bin/echo "*******************************************************************************"
+    /bin/echo "**                        Configuring Login Manager                          **"
+    /bin/echo "*******************************************************************************"
 
-cat > /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf << EOF
+    /bin/cat > /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf << EOF
 [SeatDefaults]
 greeter-session=unity-greeter
 allow-guest=false
 greeter-show-remote-login=false
 greeter-show-manual-login=true
 EOF
+fi
+exit 0
